# ╭─────────────────────────          ImplementationGuide Notes         ───────────────────────────╮
# | This is an initial configuration file for the Pacific Base IG.                                 |
# | The id, packageId, canonical URL, name, etc. need to be validated/agreed by the Fiji IG team.  |
# | The canonical URL will need to be changed once a suitable URL is agreed upon and available.    |
# | The menu structure will be customized as required to fit the content of the IG.                |
# | The version should be updated for each release of the IG, in accord with versioning policy.    |
# | Keep the fhirVersion and instanceOptions settings unless specific reasons to change them.      |
# ╰───────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.pacific.core
packageId: hl7.fhir.uv.pacific.core
canonical: https://fijiig.github.io/fiji-pacific-ig
name: FijiPacificCore
title: Fiji Pacific Core Implementation Guide
description: Implementation Guide for Fiji FHIR Interopeerability with base definitions applicable to the wider South Pacific region.
status: draft # draft | active | retired | unknown
version: 0.2.1
copyrightYear: 2026+
releaseLabel: ci-build
license: CC0-1.0
copyright: Distributed under the Creative Commons CC0-1.0 License (https://creativecommons.org/publicdomain/zero/1.0/)

# publisher information
publisher:
  name: HealthInfoServices
  url: https://healthinfoservices.net

menu:
  Home: index.html
  Getting Started: gettingstarted.html
  Data Types: datatypes.html
  Resources: resources.html
  Terminology: terminology.html
  Extensions: extensions.html
  Artifacts: artifacts.html

# contact
contact:
  - name: Support
    telecom:
      - system: url
        value: https://www.healthinfoservices.net


# leave these settings as is unless you know what you're doing and have a reason to change them
fhirVersion: 4.0.1
instanceOptions:
  manualSliceOrdering: true

pages:
  index.md:
    title: Fiji/Pacific Core Implementation Guide
  gettingstarted.md:
    title: Contributing to the Fiji/Pacific Core IG
  datatypes.md:
    title: Data Type Profiles
  resources.md:
    title: Resource Profiles
  terminology.md:
    title: Terminology
  extensions.md:
    title: Extensions
  

#   implementation.xml:
#   examples.xml:
#     title: Examples Overview
#     simpleExamples.xml:
#     complexExamples.xml:

jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World"